### ISSUE TITLE
Documentation in English language? Examples?

### ISSUE THREAD

**Issue by cayolblake** [wind-framework/wind-framework#4]
Hello @xpader 

Is there a plan to have documentation in English language?

Also, is it possible to have examples on how to use the framework?

**Comment by xpader** [comment]
There's no definite plan to write english documentation, but  it is also possible if there is enough time.
But before this we still have lots of work to do:
- 1.0 version base on php 8.1 fiber, no need `yield` and `call()`.
- Create project through composer.
- Some components refactor, like `Container` remove depends from `php-di`, because some have to much depends, adapter php8.1 it too slow.

**Comment by cayolblake** [comment]
Okay I see.

Are there existing documentation I can translate.

Also are there examples?

Do you have a timeline for the todo list?

**Comment by xpader** [comment]
There's a doc project here: https://github.com/wind-framework/docs
And github pages: https://wind-framework.github.io/docs/#/
But it's not finished.

There is a simple todo list here: https://github.com/wind-framework/wind-framework/projects/1 , it's just some recortds..

This framework strongly depends on some third-party components, especially amphp.
So 1.0 release time depends on that.
